[project]
name = "proyecto_integracion_datos"
version = "0.1.0"
description = "Backend de integraciÃ³n de datos (INUMET, UAM, MEF)"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "pandas==2.2.2",
  "requests==2.32.3",
]